"""
Django settings for _05_django_session project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$9hdl^en*jwy(4gp9n($$tlrkekm(bd84xepj^aj)k7zu5xz#+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_05_django_session.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_05_django_session.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Django Session 설정
# 세션은 로그인 상태처럼 사용자별로 유지해야 하는 정보를 저장하는 기능이다.

# 세션 데이터 저장 위치 설정
# 기본값: 'django.contrib.sessions.backends.db'
# 주요 옵션:
# - db: DB의 django_session 테이블에 저장
# - cache: 캐시에만 저장
# - cached_db: 캐시 + DB 함께 사용
# - file: 파일에 저장
# - signed_cookies: 쿠키에 세션 데이터 저장
SESSION_ENGINE = 'django.contrib.sessions.backends.db'


# 세션 쿠키 유지 시간
# 기본값: 1209600초 = 2주
# 값을 줄이면 로그인 유지 시간이 짧아지고, 늘리면 더 오래 유지된다.
SESSION_COOKIE_AGE = 1209600


# 브라우저 종료 시 세션 만료 여부
# 기본값: False
# False: 브라우저를 닫아도 SESSION_COOKIE_AGE 동안 세션 유지
# True: 브라우저를 닫으면 세션 만료
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


# 매 요청마다 세션 저장 여부
# 기본값: False
# False: 세션 값이 변경된 경우에만 저장
# True: 매 요청마다 저장하며 세션 만료 시간이 갱신될 수 있음
SESSION_SAVE_EVERY_REQUEST = False


# JavaScript에서 세션 쿠키 접근 차단 여부
# 기본값: True
# True: document.cookie로 sessionid 접근 불가, XSS 피해 완화
# False: JS에서 쿠키 접근 가능하므로 보안상 권장하지 않음
SESSION_COOKIE_HTTPONLY = True


# SameSite 쿠키 정책
# 기본값: 'Lax'
# 다른 사이트에서 요청이 발생했을 때 쿠키를 함께 보낼지 제한한다.
#
# 주요 옵션:
# - 'Lax': 일반 링크 이동 GET 요청에는 쿠키 허용, 외부 사이트의 POST 요청 등은 제한
# - 'Strict': 같은 사이트 요청에만 쿠키 전송, 보안은 강하지만 사용성이 떨어질 수 있음
# - 'None': 모든 사이트 요청에 쿠키 전송 가능, 반드시 Secure=True 필요
#
# CSRF를 완전히 막는 설정은 아니고, CSRF 위험을 줄이는 보조 방어 수단이다.
# Django의 CSRF 토큰과 함께 사용하는 것이 기본이다.
SESSION_COOKIE_SAMESITE = 'Lax'