"""
Django settings for _04_qna project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*ou=lj_!eo^qy^!-o-+ym0*5(@bpd7)cpm3b-(cl)xn&^7nyi$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'qna',
    'uauth'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_04_qna.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_04_qna.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'qnadb',
        'USER': 'django',
        'PASSWORD': 'django',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# 개발 편의를 위해 패스워드 검증 완화
AUTH_PASSWORD_VALIDATORS = [
    {
        # 사용자 이름과 유사한 패스워드 허용하지 않음
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # 최소 길이 요구
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS' : {
            'min_length' : 4, # 최소 길이 설정 (기본 값: 8)
        }
    },
    # {
    #     # 일반적으로 사용되는 패스워드 허용 되지 않음 (예: 'password', '12345678')
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     # 숫자로만 이루어진 패스워드 허용 되지 않음
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# ORM 쿼리 로그 출력 (형식 지정)
# pip install sqlparse
import sqlparse

class SQLFormatter:
    def format(self, record):
        if record.sql:
            formatted_sql = sqlparse.format(
                record.sql,
                reindent=True,
                keyword_case='upper'
            )
            execution_time = getattr(record, 'duration', 0.0)  # duration 속성이 없는 경우 대비
            return f"{formatted_sql}\n[Execution Time: {execution_time:.3f} ms]"

        return record.getMessage()


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'custom_sql',
        },
    },

    'formatters': {
        'custom_sql': {
            '()': SQLFormatter,  # 직접 만든 SQLFormatter 클래스 사용
        },
    },

    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
    },
}

# 로그인 후 리다이렉트 URL 설정 (기본 값: /accounts/profile/)
LOGIN_REDIRECT_URL = '/'    

# 파일 업로드 관련 설정
MEDIA_URL = '/media/'               # 사용자가 접근하는 URL 경로
MEDIA_ROOT = BASE_DIR / 'media'     # 서버에 파일이 저장 되는 실제 폴더 경로